'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {MemorySetup,hash}=require('../core.cjs');
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'claudian-upgrade-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const core=new MemorySetup({home:root,dataDir:path.join(root,'data')});const input={name:'User',vault:path.join(root,'notes'),mode:'new',storage:'obsidian',language:'en',hosts:['codex','cursor']};await core.install((await core.prepare(input)).id);let profile=(await core.snapshot()).profile;profile.protocolVersion='1.2.0';for(const f of profile.files.filter(f=>f.type==='skill')){await fs.writeFile(f.path,'old owned skill');f.hash=hash('old owned skill');}await fs.writeFile(core.configFile,JSON.stringify(profile));return {core,profile,root};}
test('owned legacy skill migrates once and keeps notes and hosts',async t=>{const {core,profile}=await fixture(t);const note=path.join(profile.vault,'Claudian About me.md');await fs.writeFile(note,'My own facts');const result=await core.upgrade();assert.ok(result.changed>0);assert.equal(await fs.readFile(note,'utf8'),'My own facts');assert.ok(!result.conflicts.includes(note));assert.equal((await core.snapshot()).profile.hosts.length,2);assert.match(await fs.readFile(profile.hosts[0].artifacts.skill,'utf8'),/INVALIDATE/);assert.equal((await core.upgrade()).changed,0);});
test('custom skill is preserved automatically; explicit repair backs it up',async t=>{const {core,profile}=await fixture(t);const file=profile.hosts[0].artifacts.skill;await fs.writeFile(file,'My custom instructions');assert.ok((await core.upgrade()).conflicts.includes(file));assert.equal(await fs.readFile(file,'utf8'),'My custom instructions');assert.equal((await core.upgrade('codex')).conflicts.length,0);assert.match(await fs.readFile(file,'utf8'),/Claudian Universal Protocol/);const dirs=await fs.readdir(path.join(core.dataDir,'upgrades'));let backup=false;for(const dir of dirs){const journal=JSON.parse(await fs.readFile(path.join(core.dataDir,'upgrades',dir,'journal.json')));backup ||=journal.changes.some(c=>c.before==='My custom instructions');}assert.ok(backup);});
test('repair recreates missing skill and preserves external rule edits on later removal',async t=>{const {core,profile}=await fixture(t);const {skill,rule}=profile.hosts[0].artifacts;await fs.unlink(skill);await fs.appendFile(rule,'\nUnrelated user instruction.\n');await core.upgrade('codex');assert.match(await fs.readFile(skill,'utf8'),/name: claudian-memory/);await core.removeHost('codex');assert.match(await fs.readFile(rule,'utf8'),/Unrelated user instruction/);assert.doesNotMatch(await fs.readFile(rule,'utf8'),/claudian:memory:start/);});
test('malformed rule blocks are not guessed or destroyed by repair',async t=>{const {core,profile}=await fixture(t);const file=profile.hosts[0].artifacts.rule;await fs.writeFile(file,'User rules\n<!-- claudian:memory:start -->\nbroken');const before=await fs.readFile(file,'utf8');assert.ok((await core.upgrade('codex')).conflicts.includes(file));assert.equal(await fs.readFile(file,'utf8'),before);});
test('new protocol defines no-op, invalidation, forgetting and silent failure boundary',async t=>{const {profile}=await fixture(t);const text=await fs.readFile(path.join(profile.vault,'Claudian Universal Protocol.md'),'utf8');for(const term of ['NO_OP','INVALIDATE','valid_from','user_statement','forget/delete','failed save'])assert.ok(text.includes(term),term);});
