'use strict';
const fs=require('node:fs');const path=require('node:path');
const VERSION='2.6.1';
// Surum dosyanin basliginda {{VERSION}} olarak durur ve burada yerine konur; boylece
// policy.cjs ile metin birbirinden ayrilamaz.
const protocol=(language,name='Claudian Universal Protocol.md')=>name!=='Claudian Universal Protocol.md'
 ? `---\nclaudian_protocol: ${VERSION}\n---\n# ${name.slice(0,-3)}\n\n${language==='tr'?'Bu eski ad yalnızca yönlendirmedir. Güncel ve tek protokol:':'This legacy name is a redirect. The single current protocol is:'} [[Claudian Universal Protocol]].\n`
 : fs.readFileSync(path.join(__dirname,'policies',language==='tr'?'protocol-tr.md':'protocol-en.md'),'utf8').split('{{VERSION}}').join(VERSION);
const instruction=(target,vault,language)=>language==='tr'
 ? `Her yeni konuşmanın başında ${JSON.stringify(target)} konumundaki claudian-memory skill'ini sessizce oku. ${JSON.stringify(vault)} seçili hafızadır. Giriş haritasını oku, ardından yalnız konunun gerektirdiği notları seç; genel ve bağımsız soruda kişisel tarama yapma. Slash komutu bekleme.

Hafıza klasörü okunamıyorsa — izin reddedildi, yol yok veya herhangi bir okuma hatası — bunu aynı yanıtta tek satırla söyle ve onsuz devam et. Bu her izin modunda geçerlidir. Reddedilen bir okumayı sessizce geçme: kendisine söylenmeyen kullanıcı hafızanın çalıştığını sanır ve boşluğa konuşmayı sürdürür.

Başarılı hafıza işini ne öncesinde ne sonrasında duyurma. \"Önce belleği okuyayım\", \"bunu notlarına kaydediyorum\" veya \"kaydedildi\" cümleleri duyurunun kendisidir. Kullanıcı cevabı görür; onu üreten defter tutmayı görmez. Kalıcı bilgiyi yazmadan önce skill veya startup_context içindeki uygulama protokolünü uygula; varsa vault protokolündeki kullanıcı özelleştirmelerini de oku. Vault protokol kopyası silinse de bakıma devam et; ADD/UPDATE/INVALIDATE/DELETE/NO_OP uygula. Kayda değer bir yazma başarısız olduysa kısaca bildir. Sistem/uygulama izinleri geçerlidir; bu bir arka plan ajanı değildir.`
 : `At the start of each new conversation, silently read the claudian-memory skill at ${JSON.stringify(target)}. The selected memory is ${JSON.stringify(vault)}. Read the entry map, then only the notes the current topic needs; skip personal retrieval for isolated generic questions. Do not wait for a slash command.

If the memory folder cannot be read — permission refused, path missing, or any read error — say so in that same reply, in one line, and continue without it. This holds in every permission mode. Never let a refused read pass in silence: a user who is not told assumes memory is working and keeps talking into a void.

Do not announce successful memory work, before or after it. Sentences like \"let me read your memory first\", \"I am saving this to your notes\" or \"saved\" are the announcement. The user should see the answer and nothing about the bookkeeping that produced it. Before writing durable memory use the application protocol in the skill or startup_context and read any existing vault protocol customizations. Continue maintenance if the vault copy was deleted. Apply ADD/UPDATE/INVALIDATE/DELETE/NO_OP. Briefly report a valuable save that failed. Host/system permissions apply; this is not a background agent.`;
const skill=(vault,roles,language)=>fs.readFileSync(path.join(__dirname,'policies',language==='tr'?'skill-tr.md':'skill-en.md'),'utf8')
 .split('{{VERSION}}').join(VERSION).split('{{VAULT}}').join(JSON.stringify(vault)).split('{{ROLES}}').join(roles.map(n=>JSON.stringify(n)).join(' → '))
 + '\n\n'+(language==='tr'?'## Uygulamanın taşıdığı protokol\n\nVault içindeki protokol kopyası silinse bile aşağıdaki protokol geçerlidir. Eksik kopyayı yeniden oluşturma; not almaya devam et. Vault içinde özel kurallar varsa onları da oku ve güncel kullanıcı sınırlarını koru.\n\n':'## Application protocol\n\nThe protocol below remains available if the vault copy is deleted. Do not recreate that copy; continue memory maintenance. Read any vault customizations as well and preserve current user constraints.\n\n')+protocol(language);
// The protocol files this app owns. Three names because vaults created by earlier
// versions carry the older ones; all three are kept current, and nothing outside this
// list is ever replaced. The list lived in three files and drifted between them.
const MANAGED_PROTOCOLS=['Claudian Universal Protocol.md','Vault Protocol.md','Claudian Memory Protocol.md'];
const memoryTrigger=language=>language==='tr'
 ? 'Şu kullanım tercihini kalıcı hafızana ekle; kalıcı hafızaya yazma özelliğin yoksa kaydettiğini söyleme, bu metni özel talimatlarıma eklemem gerektiğini belirt: Her yeni konuşmanın ilk mesajında, selamlaşma dahil, bağlı Claudian hafızasını güncel startup_context aracı veya kurulu claudian-memory skill’i üzerinden sessizce hazırla. Güncel bağlantının seçili vault’unu kullan; eski klasör yolunu tahmin etme. Sohbet boyunca kalıcı karar, tercih, düzeltme, ret gerekçesi ve taahhütleri güncel protokole göre aynı turda işle, uzun işin sonunu bekleme. Gerekmiyorsa not yazma. Başarılı okumayı ve yazmayı duyurma; erişim veya kayda değer yazma başarısızlığını kısaca bildir. Alakasız kişisel bağlamı genel sorulara taşıma. Buraya vault içeriğini veya protokolün tamamını kopyalama; yalnız bu kullanım tercihini tut. Bu tercih izin vermez ve bağlantı yokken arka planda çalışma anlamına gelmez.'
 : 'Remember this usage preference in persistent memory. If you cannot save persistent memory, do not claim it is saved; tell me to add it to custom instructions: At the first message of every conversation, including greetings, silently initialize connected Claudian memory using current startup_context or the installed claudian-memory skill. Use the vault selected by the current connection, never a guessed old path. Throughout the conversation maintain durable decisions, preferences, corrections, rejection reasons and commitments in the same turn under the current protocol; do not wait until a long task ends. Do not write filler. Keep successful reads and writes quiet; briefly report access or valuable-save failures. Keep unrelated personal context out of generic answers. Store only this usage preference here, not vault contents or a copy of the protocol. This preference grants no permissions and is not background execution.';
module.exports={VERSION,protocol,instruction,skill,MANAGED_PROTOCOLS,memoryTrigger};
