'use strict';
const { contextBridge, ipcRenderer } = require('electron');
const invoke = async (channel, ...args) => {
  const result = await ipcRenderer.invoke(channel, ...args);
  if (!result.ok) throw new Error(result.error);
  return result.value;
};
contextBridge.exposeInMainWorld('claudian', {
  ringStatus: () => invoke('ring:status'),
  ringChooseEngine: () => invoke('ring:choose-engine'),
  ringChooseAudio: () => invoke('ring:choose-audio'),
  ringRun: input => invoke('ring:run', input),
  ringCancel: () => invoke('ring:cancel'),
  ringDrafts: () => invoke('ring:drafts'),
  ringDraft: id => invoke('ring:draft', id),
  ringApprove: (id, choice) => invoke('ring:approve', id, choice),
  ringDiscard: id => invoke('ring:discard', id),
  ringReceiverStart: () => invoke('ring:receiver-start'),
  ringReceiverStop: () => invoke('ring:receiver-stop'),
  ringPackage: () => invoke('ring:package'),
  onRingEvent: fn => { const h = (_e, v) => fn(v); ipcRenderer.on('ring:event', h); return () => ipcRenderer.removeListener('ring:event', h); },
  tunnelStatus: () => invoke('tunnel:status'),
  tunnelSave: input => invoke('tunnel:save',input),
  tunnelStart: () => invoke('tunnel:start'),
  tunnelStop: () => invoke('tunnel:stop'),
  tunnelForget: () => invoke('tunnel:forget'),
  tunnelChoose: () => invoke('tunnel:choose'),
  tunnelGuide: () => invoke('tunnel:guide'),
  geminiLogin: () => invoke('memory:gemini-login'),
  geminiGuide:()=>invoke('connector:gemini-guide'),
  connectorSetupHelp: provider => invoke('connector:setup-help',provider),
  connectorStatus: () => invoke('connector:status'),
  connectorDesktopInstall: () => invoke('connector:desktop-install'),
  connectorStart: url => invoke('connector:start',url),
  connectorStop: () => invoke('connector:stop'),
  connectorApprove: (id,allowed) => invoke('connector:approve',id,allowed),
  connectorRevoke: id => invoke('connector:revoke',id),
  connectorExport: provider => invoke('connector:export',provider),
  connectorProvider: provider => invoke('connector:provider',provider),
  obsidianInstalled: () => invoke('app:obsidian-installed'),
  state: () => invoke('app:state'),
  reportObsidian: value => invoke('app:obsidian-state', value),
  downloadObsidian: () => invoke('app:download-obsidian'),
  scanPreview: language => invoke('memory:scan-preview',language),
  reviewStart: id => invoke('memory:review-start',id),
  reviewStatus: id => invoke('memory:review-status',id),
  chooseCli: id => invoke('memory:choose-cli',id),
  existingSkill: id => invoke('memory:existing-skill',id),
  scanSend: (id,prompt) => invoke('memory:scan-send',id,prompt),
  memoryTrigger: host => invoke('memory:trigger', host),
  openAiApp: id => invoke('memory:open-app',id),
  repair: host => invoke('memory:repair',host),
  updates: () => invoke('app:updates'),
  downloadUpdate: () => invoke('app:download-update'),
  snapshot: () => invoke('app:snapshot'),
  reviewSetup: (hosts, consent, withdraw) => invoke('setup:review', hosts, consent, withdraw),
  finishReview: () => invoke('setup:review-done'),
  preferences: language => invoke('app:preferences', language),
  connections: () => invoke('memory:connections'),
  selfCheck: () => invoke('memory:self-check'),
  checkFiles: () => invoke('memory:check-files'),
  removeHost: host => invoke('memory:remove', host),
  configuration: (host, kind) => invoke('memory:configuration', host, kind),
  obsidian: () => invoke('memory:obsidian'),
  discover: () => invoke('app:discover'),
  enter: view => invoke('app:enter', view),
  chooseFolder: () => invoke('app:folder'),
  relocate: target => invoke('memory:relocate', target),
  verifyWatch: (host,requestId) => invoke('memory:verify-watch', host,requestId),
  cancelVerify: host => invoke('memory:verify-cancel',host),
  prepare: input => invoke('setup:prepare', input),
  install: (id, consent) => invoke('setup:install', id, consent),
  cancel: () => invoke('setup:cancel'),
  activity: () => invoke('memory:activity'),
  health: () => invoke('memory:health'),
  notice: () => invoke('memory:notice'),
  adoptProtocol: () => invoke('memory:adopt-protocol'),
  skipVerification: () => invoke('memory:skip-verification'),
  challenge: host => invoke('memory:challenge', host),
  verify: host => invoke('memory:verify', host),
  copy: text => invoke('app:copy', text),
  open: kind => invoke('app:open', kind),
  onVerify: callback => {
    const listener = (_event, value) => callback(value);
    ipcRenderer.on('verify:event', listener);
    return () => ipcRenderer.removeListener('verify:event', listener);
  },
  onProgress: callback => {
    const listener = (_event, value) => callback(value);
    ipcRenderer.on('setup:event', listener);
    return () => ipcRenderer.removeListener('setup:event', listener);
  },
});
