'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
exports.run=async({win,core,app,home})=>{const output=process.env.CLAUDIAN_SMOKE_OUTPUT||path.join(core.dataDir,'smoke-output');await fs.mkdir(output,{recursive:true});const js=s=>win.webContents.executeJavaScript(s).catch(e=>{throw Error(s+' :: '+e.message)});const wait=async s=>{const end=Date.now()+15000;while(Date.now()<end){if(await js(s))return;await new Promise(r=>setTimeout(r,80));}throw Error('UI timeout: '+s);};const click=async s=>{await wait(`!!document.querySelector(${JSON.stringify(s)})`);return js(`document.querySelector(${JSON.stringify(s)}).click()`);};try{
 await wait('!!document.querySelector("#name")');assert.equal(await js('document.documentElement.lang'),'en');
 await js(`document.querySelector('#name').value='Deniz';document.querySelector('#vault').value=${JSON.stringify(path.join(home,'Notes'))};document.querySelectorAll('[name=host]').forEach(x=>x.checked=true)`);
 await click('[data-action=preview]');await wait('!!document.querySelector("[data-action=install]")');assert.ok(await js('!!document.querySelector(".grant-consent")'),'onay blogu onizlemede olmali');assert.ok(await js('document.querySelectorAll(".grant-consent .caps li").length>=6'),'yetenekler listelenmeli');await js('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');await new Promise(r=>setTimeout(r,300));await js('document.querySelector(".grant-consent").scrollIntoView({block:"center"})');await new Promise(r=>setTimeout(r,200));await fs.writeFile(path.join(output,'consent.png'),(await win.webContents.capturePage()).toPNG());await click('[data-action=back]');await wait('!!document.querySelector("#name")');await click('[data-action=preview]');await wait('!!document.querySelector("[data-action=install]")');await click('[data-action=install]');await wait('!!document.querySelector("[data-action=enter-verify]")');assert.ok(await js('!!document.querySelector("[data-action=enter-verify]")'),'setup ends on the proof step');await click('[data-action=skip-verify]');await wait('!!document.querySelector("[data-view=connections]")');await click('[data-view=connections]');await wait('!!document.querySelector("[data-action=remove]")');assert.equal((await core.snapshot()).profile.hosts.length,Object.keys(require('./core.cjs').HOSTS).length);
 await click('[data-view=home]');await wait('!!document.querySelector("[data-action=obsidian]")');assert.ok(await js('!!document.querySelector("[data-action=obsidian]")'),'memory view');assert.ok(await js('!!document.querySelector(".health-warn")'),'a fresh install has proven nothing and says so');assert.ok(await js('!document.querySelector(".health-warn").textContent.includes("write to your notes")'),'the warning is about proof, not a broken folder');
 assert.ok((await js('window.claudian.obsidian()')).startsWith('obsidian://open?path='));assert.ok(await js('window.claudian.configuration("codex","skill")'));
 await click('[data-view=connections]');await wait('!!document.querySelector("[data-action=remove]")');await click('[data-action=remove][data-host=cursor]');await click('[data-action=dismiss-remove]');assert.equal((await core.snapshot()).profile.hosts.length,Object.keys(require('./core.cjs').HOSTS).length);await click('[data-action=remove][data-host=cursor]');await click('[data-action=confirm-remove]');await wait('!document.querySelector("[data-action=remove][data-host=cursor]")');
 await click('[data-action=add-hosts]');await wait('!!document.querySelector("[name=host][value=cursor]")');await js('document.querySelector("[name=host][value=cursor]").checked=true');await click('[data-action=preview]');await wait('!!document.querySelector("[data-action=install]")');await click('[data-action=install]');await wait('!!document.querySelector("[data-action=enter-verify]")');await click('[data-action=skip-verify]');await wait('!!document.querySelector("[data-action=remove][data-host=cursor]")');
 await win.loadURL('claudian://app/index.html');await wait('!!document.querySelector("[data-view=connections]")');await click('[data-view=connections]');await wait('!!document.querySelector("[data-action=remove]")');assert.equal(await js('typeof require'),'undefined');assert.equal(await js('document.querySelector("#error").hidden'),true);
 await click('[data-view=companion]');
 // The embedded web companion panel was withdrawn on 10.09.2026 and the companion screen
 // is a local, under-construction surface. The invariant worth guarding is that no remote
 // view comes back and that the access code form is the only input offered here.
 await wait('!!document.querySelector("#core-form")');
 assert.equal(await js('getComputedStyle(document.querySelector("nav .development-label")).display'),'inline');
 assert.ok(await js('!!document.querySelector("#core-code")'));
 assert.ok(await js('!!document.querySelector(".development-label")'));
 assert.equal(win.contentView.children.filter(v=>v.webContents&&v.webContents!==win.webContents).length,0,'no embedded remote view');
 assert.equal(await js('typeof require'),'undefined');
 assert.equal(await js('typeof window.claudian.internal'),'undefined');
 await click('[data-view=home]');await wait('!!document.querySelector("[data-action=obsidian]")');
 await click('[data-view=connections]');await wait('!!document.querySelector("[data-action=remove]")');await click('[data-action=challenge-start][data-host=codex]');await wait('!!document.querySelector(".verify-row pre.prompt")');assert.ok(await js('document.querySelector(".verify-row pre.prompt").textContent.includes("claudian-check")'));await fs.writeFile(path.join(output,'verify.png'),(await win.webContents.capturePage()).toPNG());await wait('!!document.querySelector(".verify-row .verify-status")');assert.ok(await js('!!document.querySelector(".verify-row .verify-status").textContent'),'durum satiri kendiliginden belirmeli');assert.ok(await js('!!document.querySelector(".verify-row .verify-spinner")'),'beklerken bir hareket gostergesi olmali');await click('[data-action=challenge-close]');await wait('!document.querySelector(".verify-row pre.prompt")');assert.ok(await js('!!document.querySelector(".usage")'),'kullanim satiri gorunur olmali');assert.ok(await js('!!document.querySelector(".usage").closest("details")'),'kullanim ayrintilari acilabilir olmali');assert.ok(await js('document.querySelector(".caps-row").textContent.includes("startup_context")'),'teknik yetenekler yapilandirmada bulunmali');assert.ok(await js('!document.querySelector("[data-action=challenge-start][data-host=chatgpt]")'),'unavailable relay must not offer a working connection test');assert.ok(await js('!document.body.textContent.includes("https://claudian.app/mcp")'),'no invented remote endpoint');await fs.writeFile(path.join(output,'connections.png'),(await win.webContents.capturePage()).toPNG());await js('window.scrollTo(0,document.body.scrollHeight)');await new Promise(r=>setTimeout(r,300));await fs.writeFile(path.join(output,'connections-bottom.png'),(await win.webContents.capturePage()).toPNG());await click('[data-view=home]');await wait('!!document.querySelector("[data-action=obsidian]")');await fs.writeFile(path.join(output,'panel.png'),(await win.webContents.capturePage()).toPNG());await fs.writeFile(path.join(output,'result.json'),JSON.stringify({passed:true,checks:['startup language is deterministic','preview back','six-host installation','silent local probe','Obsidian URI','configuration target','companion has no embedded remote view','removal cancellation','remove and reconnect','restart persistence','renderer isolation']}));console.log('SMOKE PASS '+output);app.exit(0);
 }catch(e){console.error(e);try{console.error('RENDERER ERROR: '+await win.webContents.executeJavaScript('(document.querySelector("#error")||{}).textContent||"(bos)"'));console.error('VIEW: '+await win.webContents.executeJavaScript('(document.querySelector("nav .active")||{}).dataset?.view||"(yok)"'));console.error('ACTIONS: '+await win.webContents.executeJavaScript('[...document.querySelectorAll("[data-action]")].map(n=>n.dataset.action).join(",")'));}catch{}await fs.writeFile(path.join(output,'failure.png'),(await win.webContents.capturePage()).toPNG());app.exit(1);}};
