'use strict';
// The starter memory, shaped like the vault it was learned from.
//
// The earlier starter was nine flat notes and a protocol. It worked as a place to put things
// and failed as a place to find them: there was no map of the system itself, no note saying
// what this thing is and is not, nowhere to record which AI surface actually works, and the
// two panels were one line each. The reference vault this product came from carries all of
// those, and they are the reason an agent can be consistent in it.
//
// What is carried over is the SHAPE and the RULE BODY. Nothing personal crosses: no name but
// the one the user typed, no history, no opinions, no examples drawn from one person's life.
// Every note here has to earn its place by changing what an agent does.
//
// Every managed note declares `claudian_role`. That is what the skill and the protocol resolve;
// the filename is only what the user sees, so they may rename or translate any of these.
const ROLES = ['start', 'entry', 'panel', 'reminders', 'agreements', 'decisions', 'about', 'projects', 'lessons', 'system', 'graph', 'tools', 'guide', 'claudian'];

const front = (language, {tags, kind, role}) => {
  const tr = language === 'tr';
  return `---\ntags: [${tags.join(', ')}]\n${tr ? 'tür' : 'type'}: ${kind}\nclaudian_role: ${role}\n${tr ? 'güncellenme' : 'updated'}: ${new Date().toISOString().slice(0, 10)}\n---\n\n`;
};

// The entry map is named after the person so it sorts to the top of their own folder, the way
// a home note does. "00 -" is not decoration: it keeps the map first in an alphabetical list.
const entryName = (language, name) => `00 - ${name || (language === 'tr' ? 'Merkez' : 'Hub')}${name ? (language === 'tr' ? ' (Merkez)' : ' (Hub)') : ''}.md`;

const notes = (language, name) => {
  const tr = language === 'tr';
  const map = entryName(language, name);
  const link = file => `[[${file.replace(/\.md$/, '')}]]`;
  const n = tr
    ? {start: 'Buradan Başla.md', panel: 'Kontrol Paneli.md', reminders: 'Hatırlatıcılar.md', agreements: 'Çalışma Anlaşmaları.md',
       decisions: 'Kararlar.md', about: 'Hakkımda.md', projects: 'Projeler.md', lessons: 'Öğrenilenler.md',
       system: 'Sistem.md', graph: 'Graph View.md', tools: 'Bağlı Araçlar.md', guide: 'Kayıt Rehberi.md',
       claudian: 'Claudian.md', protocol: 'Vault Protokolü.md'}
    : {start: 'Start Here.md', panel: 'Control Panel.md', reminders: 'Reminders.md', agreements: 'Working Agreements.md',
       decisions: 'Decisions.md', about: 'About Me.md', projects: 'Projects.md', lessons: 'Lessons.md',
       system: 'System.md', graph: 'Graph View.md', tools: 'Connected Tools.md', guide: 'Record Guide.md',
       claudian: 'Claudian.md', protocol: 'Vault Protocol.md'};

  const out = {};
  const add = (file, meta, body) => { out[file] = front(language, meta) + body; };

  add(n.start, {tags: ['claudian', tr ? 'giriş' : 'entry'], kind: tr ? 'sistem' : 'system', role: 'start'}, tr
    ? `# Buradan Başla\n\nBu klasör senin hafızan. AI uygulamaların buraya yazar, buradan okur — sen istemesen de, her konuşmanın başında sessizce.\n\n1. Merkez harita: ${link(map)} — her şey oradan dallanır.\n2. Bu beyni görsel olarak görmek için: ${link(n.graph)}\n3. Neyin yazılıp neyin yazılmadığı: ${link(n.protocol)}\n4. Sistemin kendisi nasıl çalışıyor: ${link(n.system)}\n\n> İpucu: bir kelimeyi \`[[çift köşeli parantez]]\` içine alınca yeni bir not ve yeni bir bağlantı doğar. Yapı böyle büyür; klasör açman gerekmez.\n\nBurada yazan hiçbir şey bağlayıcı değil. Bir not seninle çelişirse haklı olan sensin; not düzeltilir.\n`
    : `# Start Here\n\nThis folder is your memory. Your AI applications write to it and read from it — quietly, at the start of every conversation, without being asked.\n\n1. The entry map: ${link(map)} — everything branches from there.\n2. To see this as a picture: ${link(n.graph)}\n3. What gets written and what does not: ${link(n.protocol)}\n4. How the system itself works: ${link(n.system)}\n\n> Tip: wrap a phrase in \`[[double brackets]]\` and a new note and a new link appear. That is how the structure grows; you never need to make folders.\n\nNothing written here is binding. If a note contradicts you, you are right and the note is what changes.\n`);

  add(map, {tags: ['claudian', tr ? 'merkez' : 'hub'], kind: 'moc', role: 'entry'}, tr
    ? `# ${name ? name + ' — hafıza' : 'Hafıza'}\n\nBu hafızanın giriş noktası. Buradan dallanır; en çok bağlantısı olan düğüm budur.\n\n## Kim\n\n${link(n.about)}\n\n## Ajanda\n\n${link(n.panel)} — tarihi olmayan açık döngüler\n${link(n.reminders)} — tarihli işler\n\n## Nöronlar\n\n- ${link(n.projects)} — süregelen ve biten işler\n- ${link(n.decisions)} — verilmiş kararlar ve reddedilen yönler\n- ${link(n.lessons)} — bir kez ödenmiş bedeller\n- ${link(n.agreements)} — nasıl çalışılacağına dair kalıcı talimatlar\n- ${link(n.system)} — bu hafızanın kendisi\n\n## İlke\n\nBu hafıza canlı ama otorite değil. Notlar AI tarafından yazıldı; birer hatırlatma, kanıt değil. Kural ${link(n.protocol)} içinde.\n\n---\n> Her şey birbirine bağlanmak zorunda değil. Konu bütünlüğü oluşunca bağlanır; ayrı kümeler ayrı durabilir.\n`
    : `# ${name ? name + ' — memory' : 'Memory'}\n\nThe entry point of this memory. Everything branches from here; this is the node with the most links.\n\n## Who\n\n${link(n.about)}\n\n## Agenda\n\n${link(n.panel)} — open loops without a date\n${link(n.reminders)} — work that has a date\n\n## Neurons\n\n- ${link(n.projects)} — work in progress and work finished\n- ${link(n.decisions)} — decisions made and directions rejected\n- ${link(n.lessons)} — costs paid once\n- ${link(n.agreements)} — durable instructions about how to work with you\n- ${link(n.system)} — this memory itself\n\n## Principle\n\nThis memory is alive but not authoritative. Notes were written by an AI; they are reminders, not evidence. The rule lives in ${link(n.protocol)}.\n\n---\n> Not everything has to connect to everything. A link is made when there is real subject continuity; separate clusters may stay separate.\n`);

  add(n.system, {tags: ['claudian', tr ? 'sistem' : 'system'], kind: tr ? 'sistem' : 'system', role: 'system'}, tr
    ? `# Sistem\n\nBu hafızanın kendisi nasıl çalışıyor. Meta katman.\n\n## İşletim\n\n- ${link(n.claudian)} — sistem nedir, ne değildir\n- ${link(n.protocol)} — ne okunur, ne yazılır, ne yazılmaz; ajan-bağımsız ve bağlayıcı\n- ${link(n.guide)} — bir kaydın nasıl okunur hâle geldiği\n- ${link(n.tools)} — hangi yüzeyde hangi araç çalışıyor, hangisi kırık\n- ${link(n.panel)} — açık döngüler ve doğrulama bekleyenler\n\n## Yöntem\n\n- ${link(n.graph)} — yapıyı görsel görmek\n\n## Adaptörler\n\nHer bağlı AI uygulamasının kendi adaptör notu vardır ve yalnız o yüzeye aittir. Protokol ortaktır; adaptör yüzeye özeldir.\n\n## İlke: not otorite değil\n\nŞüpheli bilgi ${link(n.panel)} içindeki doğrulama kuyruğuna düşer ve bir kelimeyle kapanır.\n`
    : `# System\n\nHow this memory itself works. The meta layer.\n\n## Operation\n\n- ${link(n.claudian)} — what the system is and is not\n- ${link(n.protocol)} — what is read, written and never written; agent-independent and binding\n- ${link(n.guide)} — how a record becomes readable\n- ${link(n.tools)} — which tool works on which surface, and which is broken\n- ${link(n.panel)} — open loops and things awaiting confirmation\n\n## Method\n\n- ${link(n.graph)} — seeing the structure as a picture\n\n## Adapters\n\nEvery connected AI application has its own adapter note, belonging to that surface alone. The protocol is shared; the adapter is specific.\n\n## Principle: a note is not authority\n\nAnything doubtful goes to the confirmation queue in ${link(n.panel)} and closes with a single word from you.\n`);

  add(n.graph, {tags: ['claudian', tr ? 'kavram' : 'concept'], kind: tr ? 'kavram' : 'concept', role: 'graph'}, tr
    ? `# Graph View\n\nNotları düğüm, bağlantıları çizgi olarak gösteren görsel ağ ekranı. Obsidian'da sol kenardaki graph simgesinden açılır.\n\n## Ne işe yarar\n\nPlanlamadığın bağlantıları gözle yakalamak için. Ayrı kümeler ayrı durur, kesişimler köprü kurar — yapının sağlıklı mı yoksa dağınık mı olduğunu bir bakışta gösterir.\n\n## "Saç yumağı" tuzağı\n\nHer şeyi her şeye bağlarsan graph okunamaz bir yumağa döner ve anlamını kaybeder. İlke net: **her şey birbirine bağlanmak zorunda değil.** Bağlantı yalnız gerçek konu bütünlüğü olunca kurulur. Zorlama bağ bilgi değil gürültüdür.\n\n## Dürüst not\n\nBu görsel senin için. Ajan graph'ı resim olarak görmez — markdown'daki bağlantıları *metin* olarak okur. Görsel ağ insana, bağlantı yapısı ajana hitap eder.\n`
    : `# Graph View\n\nThe visual network that draws notes as nodes and links as lines. Open it from the graph icon in Obsidian's left sidebar.\n\n## What it is for\n\nCatching connections you did not plan. Separate clusters stay separate and overlaps build bridges — it shows at a glance whether the structure is healthy or scattered.\n\n## The hairball trap\n\nConnect everything to everything and the graph becomes an unreadable tangle that means nothing. The principle is plain: **not everything has to connect to everything.** A link is made only where there is real subject continuity. A forced link is noise, not information.\n\n## An honest note\n\nThis picture is for you. The agent never sees the graph as an image — it reads the links in the markdown as *text*. The visual network speaks to a person; the link structure speaks to an agent.\n`);

  add(n.claudian, {tags: ['claudian', tr ? 'sistem' : 'system'], kind: tr ? 'sistem' : 'system', role: 'claudian'}, tr
    ? `# Claudian\n\nBirden fazla AI uygulamasının ortak kullandığı, senin bilgisayarında duran hafıza. Bir uygulamaya anlattığın şeyi diğeri de bilir; bağlamı yeniden anlatmak gerekmez.\n\n## Ne yapar\n\n- Konuşmanın başında ilgili notları sessizce okur.\n- Kalıcı bir karar, tercih, düzeltme, ret gerekçesi veya tarihli bir yükümlülük çıktığında aynı turda yazar.\n- Değişen bilgiye dayanan eski kayıtları düzeltir.\n\n## Ne değildir\n\n- **Tek bir modelin günlüğü değil.** Buraya birden fazla ajan yazar; notlar nötr ve ajan-bağımsız tutulur.\n- **Sürekli çalışan bir gözcü değil.** Açık bir konuşma olmadan çalışmaz; arka planda seni izlemez.\n- **Yalnız bir not koleksiyonu değil.** Değeri protokol, ajan erişimi ve açık döngü takibinin birlikte çalışmasından gelir.\n- **Bir erişim yetkisi değil.** Hangi klasörü okuyabildiği, AI uygulamasının kendi izinlerine bağlıdır.\n\n## Sınır\n\nBir yetenek bir yüzeyde çalışıyor diye hepsinde çalışmaz. Durum ${link(n.tools)} içinde tutulur.\n`
    : `# Claudian\n\nA memory shared by more than one AI application and kept on your own computer. What you tell one application, the next one already knows; you do not re-explain the context.\n\n## What it does\n\n- Quietly reads the relevant notes at the start of a conversation.\n- Writes in the same turn when a durable decision, preference, correction, rejection reason or dated obligation appears.\n- Corrects older records that depended on what changed.\n\n## What it is not\n\n- **Not one model's diary.** More than one agent writes here; notes stay neutral and agent-independent.\n- **Not a watcher.** It does nothing without an open conversation and does not observe you in the background.\n- **Not merely a note collection.** Its value comes from the protocol, the agent's access and open-loop tracking working together.\n- **Not a permission grant.** Which folder it can read depends on each AI application's own permissions.\n\n## Boundary\n\nA capability working on one surface does not mean it works on all. That state is kept in ${link(n.tools)}.\n`);

  add(n.panel, {tags: ['claudian', tr ? 'panel' : 'panel'], kind: tr ? 'ajanda' : 'agenda', role: 'panel'}, tr
    ? `# Kontrol Paneli\n\n${link(map)}\n\nTarihi olmayan açık döngüler, doğrulama bekleyen bilgiler ve süregelen hatlar burada durur. Tarihli işler ${link(n.reminders)} içindedir; oturum başında ikisi de okunur.\n\n**Dürtme kuralı.** Buradaki kalemler konuşma başında hatırlatılabilir — boğmadan, yalnız gerçekten duranlar. Aynı kalem her oturum tekrarlanmaz. Uzun süre kapanmayan bir şey varsa bir kez sorulur ve kapatmak önerilir. Bu, "ne yapıyoruz" tarzı boş yoklamanın zıddıdır: somut kalem hatırlatılır, genel durum sorulmaz.\n\n**Yeni kalem standardı.** Bir kalem; kaynak bağlantısını, açılış tarihini ve bir sonraki anlamlı temas koşulunu taşır. Cevaplanan bilgi ilgili ana nota işlenir ve burada kapatılır. **Panel arşive dönüşmez.**\n\n## Açık döngüler\n\n## Sende bekleyen\n\nAjanın yapamayacağı, senin elini gerektiren işler.\n\n## Doğrulama bekleyen\n\nBurada yazılı ama güncelliği teyit edilmemiş bilgiler. Bir kelimeyle onaylanır ya da düzeltilir; not güncellenir, satır kapanır.\n\n## Kapanan\n`
    : `# Control Panel\n\n${link(map)}\n\nOpen loops without a date, facts awaiting confirmation, and ongoing threads live here. Dated work is in ${link(n.reminders)}; both are read at the start of a session.\n\n**The nudge rule.** Items here may be raised at the start of a conversation — without flooding, and only the ones genuinely stuck. The same item is not repeated every session. When something stays open for a long time it is asked about once, with a suggestion to close it. This is the opposite of a vague "how's it going": a concrete item is raised, never a general status check.\n\n**The standard for a new item.** An item carries its source link, the date it opened and the condition for the next meaningful contact. Once answered, the fact is written into the relevant note and the item closes here. **The panel never becomes an archive.**\n\n## Open loops\n\n## Waiting on you\n\nWork the agent cannot do, needing your hand.\n\n## Awaiting confirmation\n\nThings written here whose currency has not been confirmed. One word from you confirms or corrects it; the note is updated and the line closes.\n\n## Closed\n`);

  add(n.reminders, {tags: ['claudian', 'panel'], kind: tr ? 'ajanda' : 'agenda', role: 'reminders'}, tr
    ? `# Hatırlatıcılar\n\n${link(map)}\n\nTarihi olan işler. Her madde kendi tarihini satırında ilan eder; gerektiğinde saat dilimini taşır.\n\n**Tarih uydurulmaz.** Bilinmiyorsa yazılmaz, tahmin edilmez. Bir tarih değiştiğinde veya iptal olduğunda o madde **aynı turda** güncellenir; tamamlanan madde bu listeden çıkar.\n`
    : `# Reminders\n\n${link(map)}\n\nWork that has a date. Each item declares its own date on its line, with a timezone where it matters.\n\n**Dates are never invented.** If it is unknown it is not written and not guessed. When a date moves or is cancelled that item is updated in the **same turn**; a completed item leaves this list.\n`);

  add(n.agreements, {tags: ['claudian', tr ? 'yöntem' : 'method'], kind: tr ? 'direktif' : 'directive', role: 'agreements'}, tr
    ? `# Çalışma Anlaşmaları\n\n${link(map)}\n\nSenin kendi cümlelerinle, nasıl çalışılacağına dair kalıcı talimatlar. Bu, bu hafızadaki en değerli kayıttır ve sorularak asla elde edilemez.\n\nSorularak değil **gerçek sürtünmeden** birikir: bir düzeltme, bir ret, bir "öyle değil" geldiğinde o cümle gerekçesiyle buraya yazılır — sessizce, aynı alışveriş içinde, izin istenmeden.\n\n**Uydurulmaz.** Anlaşma ancak sen gerçekten bir şey söylediysen vardır. Tek seferlik bir yorum kalıcı kurala çevrilmez. Yeni bir düzeltme eskisiyle çeliştiğinde yenisi aktif bölümde eskisinin yerini alır; düşen cümle yalnız gerekçesi hâlâ bir hatayı önlüyorsa tarihçeye iner.\n\n## Aktif anlaşmalar\n\n## Yürürlükten düşenler — bağlayıcı değil\n`
    : `# Working Agreements\n\n${link(map)}\n\nDurable instructions about how to work with you, in your own words. This is the most valuable record in this memory, and the one that never arrives by being asked for.\n\nIt accumulates from **real friction**, not from questions: when a correction, a rejection or a "not like that" arrives, that sentence is written here with its reason — quietly, in the same exchange, without asking permission.\n\n**Never invented.** An agreement exists only when you actually said something. A single passing remark does not become a standing rule. When a later correction contradicts an earlier one, the new one replaces the old in the active section; the superseded sentence moves to history only while its reason still prevents a mistake.\n\n## Active agreements\n\n## Superseded — not binding\n`);

  add(n.decisions, {tags: ['claudian'], kind: tr ? 'kavram' : 'concept', role: 'decisions'}, tr
    ? `# Kararlar\n\n${link(map)}\n\nVerilmiş kararlar ve gerekçeleri. Kararın gerekçesi kararın kendisinden değerlidir — gerekçe, kararın ne zaman düşeceğini de söyler.\n\nBir karar geri alındığında aktif bölümden çıkar. Red gerekçesi hatanın tekrarını önlüyorsa bağlayıcı olmadığı açıkça belirtilerek tarihçede kalır. Ardından o karara **dayanan** kayıtlara bakılır: düşen bir dayanağın üstünde duran plan ve öneri askıya alınır.\n\n## Aktif\n\n## Reddedilen yaklaşımlar\n\n## Tarihçe — bağlayıcı değil\n`
    : `# Decisions\n\n${link(map)}\n\nDecisions made, with their reasons. The reason matters more than the decision — it is also what tells you when the decision falls.\n\nA reversed decision leaves the active section. When the rejection reason prevents repeating a mistake it stays in history, clearly marked as non-binding. Then whatever **depended** on it is inspected: a plan or recommendation resting on a basis that just fell is suspended rather than left active.\n\n## Active\n\n## Rejected approaches\n\n## History — not binding\n`);

  add(n.about, {tags: ['claudian'], kind: tr ? 'kişi' : 'person', role: 'about'}, tr
    ? `# Hakkımda\n\n${link(map)}\n\nSeni tanıtan kalıcı bilgiler: çalışma biçimin, kalite çıtan, teknik okuryazarlığın, tekrar eden tercihlerin. Burada yazılı olan şeyi her yeni işte baştan anlatman gerekmez.\n\nGeçici hâl buraya girmez; bir ruh hâlinin buraya girmesi için senin onu bir kimlik değerine bağlaman gerekir, ajan sıklıktan çıkarım yapmaz. Bir beğeni ise çoğu zaman bir tercihin ilk kanıtıdır ve bağlamıyla yazılır.\n\n## Tercihler\n`
    : `# About Me\n\n${link(map)}\n\nDurable things about you: how you work, your quality bar, your technical fluency, the preferences you repeat. What is written here does not have to be explained again at the start of every piece of work.\n\nA passing state does not belong here; a mood enters only when you tie it to an identity claim, and the agent does not infer it from frequency. A like, on the other hand, is often the first evidence of a preference and is written with its context.\n\n## Preferences\n`);

  add(n.projects, {tags: ['claudian'], kind: 'moc', role: 'projects'}, tr
    ? `# Projeler\n\n${link(map)}\n\nSüregelen ve biten işler. Her proje notu ihtiyacını, senin direktifini, denenip tutmayan yönü, çalışan yöntemi ve sınırını taşıyabilir — dolmayan bölüm yazılmaz.\n\nYeni bir proje notu buradan bağlanır; bağlanmayan not bulunamaz.\n`
    : `# Projects\n\n${link(map)}\n\nWork in progress and work finished. A project note may carry its need, your directive, the direction tried and abandoned, the method that worked and its boundary — a section with nothing in it is left out.\n\nA new project note is linked from here; a note nothing links to cannot be found.\n`);

  add(n.lessons, {tags: ['claudian'], kind: tr ? 'pattern' : 'pattern', role: 'lessons'}, tr
    ? `# Öğrenilenler\n\n${link(map)}\n\nBir kez ödenmiş bedeller: karşılaşılan sorun, denenip tutmayan yön ve gerekçesi, sonunda çalışan yöntem. Her ders **sınırıyla** yazılır — ne zaman geçerli değil.\n\nSınırsız bir ders altı ay sonra yanlış yönlendirir.\n`
    : `# Lessons\n\n${link(map)}\n\nCosts paid once: the problem met, the direction tried and dropped with its reason, the method that finally worked. Every lesson is written with its **boundary** — when it does not apply.\n\nA lesson without a boundary misleads six months later.\n`);

  add(n.tools, {tags: ['claudian', tr ? 'sistem' : 'system'], kind: tr ? 'sistem' : 'system', role: 'tools'}, tr
    ? `# Bağlı Araçlar\n\n${link(n.system)}\n\nAjanın eli, bağlı olduğu araçlar kadardır. Bu yüzden araç durumu takip edilen bir bilgidir — ama **aracın kendisi değil, aracın öğrenilen davranışı** yazılır.\n\n**Yetenek yüzeye bağlıdır.** Bir aracın bir uygulamada çalışması, diğerinde çalışacağı anlamına gelmez. Aynı bağlayıcı birinde tam erişim verirken diğerinde kayıtlı bile olmayabilir. Bir işi bir araca dayandırmadan önce o araç **o yüzeyde** doğrulanır.\n\n**Bir aracın bozulması bir kez ödenmiş bedeldir.** Belirti, teşhis ve varsa çözüm yazılır; ham hata dökümü değil, ikinci kez aynı duvara toslamayı önleyen teşhis.\n\n**Ne yazılmaz:** token, anahtar, oturum kimliği, OAuth referansı. Geçici ağ arızası. Kendi kendine düzelen aksaklık.\n\n| Yüzey | Araç | Ne için | Durum |\n| --- | --- | --- | --- |\n`
    : `# Connected Tools\n\n${link(n.system)}\n\nAn agent's reach is only as wide as the tools connected to it. That state is tracked here — but what is written is **not the tool, it is what was learned about the tool**.\n\n**A capability belongs to a surface.** A tool working in one application does not mean it works in the next. The same connector may grant full access in one and not even be registered in the other. Before relying on a tool, verify it **on that surface**.\n\n**A tool breaking is a cost paid once.** Record the symptom, the diagnosis and the fix if there is one; not the raw error dump, but the diagnosis that prevents hitting the same wall twice.\n\n**Never written:** tokens, keys, session identifiers, OAuth references. A transient network failure. A glitch that resolved itself.\n\n| Surface | Tool | For what | State |\n| --- | --- | --- | --- |\n`);

  add(n.guide, {tags: ['claudian', tr ? 'yöntem' : 'method'], kind: tr ? 'yöntem' : 'method', role: 'guide'}, tr
    ? `# Kayıt Rehberi\n\n${link(n.system)} · ${link(n.protocol)}\n\n## Özellikler\n\nHer not dört alan taşır: \`tags\`, \`tür\`, \`güncellenme\` ve yönetilen notlarda \`claudian_role\`. Bunlar süs değil **erişim sinyalidir** — notun türünden ve tazeliğinden seçilebilmesini sağlar. Bir notu düzenleyen aynı düzenlemede \`güncellenme\` alanını da tazeler. Rol sabittir: notu yeniden adlandırsan da bulunur.\n\n## Bir notun iskeleti\n\nİş ve yöntem notları bu bölümleri taşıyabilir. Zorunlu değil — dolmayan bölüm yazılmaz, uydurulmaz.\n\n| Bölüm | Ne taşır |\n| --- | --- |\n| Neden doğdu | hangi ihtiyaç, hangi sorun |\n| Direktif | senin kendi cümlen, alıntı olarak |\n| Denenen yön | ne denendi, neye çarpıldı, neden bırakıldı |\n| Çalışan yöntem | karar ve gerekçesi |\n| Senin adımın | elle yaptığın, onayladığın kısım |\n| Sınır | bu ne zaman geçerli değil |\n\n## Okunur hâle getirme\n\nSenin kendi cümlen \`>\` alıntı şeridinde korunur — damıtılmış özet onun yerine geçmez, çünkü kanıt olan şey tam sözlerdir. Durum ve karşılaştırma tablo olur. Komut çıktısı, log ve kod kanıt olarak fence içinde durur. Her maddenin başında kalın bir tez cümlesi olur; gerisi onu açar.\n\n## Bağlantıların görevi\n\nGiriş haritası yönlendirir; içerik tek kanonik notta yaşar. Nöronlar birer **harita**dır (MOC — Map of Content): bir konuyu toparlayıp o konunun notlarına bağlantı veren indeks notları.\n\n## Yeni bir kayıt nereye gider\n\nTutmaya değer bir bilgi, uygun not bulunamadı diye düşmez. Önce en yakın notuna tek satır olarak girer:\n\n| Bilgi | Not |\n| --- | --- |\n| tarihli iş | ${link(n.reminders)} |\n| tarihi olmayan açık iş | ${link(n.panel)} |\n| tercih, beğeni, kimlik değeri | ${link(n.about)} |\n| seninle nasıl çalışılacağı | ${link(n.agreements)} |\n| karar · reddedilen yol | ${link(n.decisions)} |\n| süregelen iş | ${link(n.projects)} |\n| bir kez ödenmiş bedel | ${link(n.lessons)} |\n\nAynı konu yeniden geldikçe satırlar birikir; o notta kendi başlığını alır. Başlık üç paragrafa çıktığında ya da aynı konuda beş-altı kayıt dağınık hissettirdiğinde kendi notu ve haritası doğar. Harita alttan, birikimle açılır; boş bir konu için üstten not açılmaz. "Ayrı not açma" ölçüsü bölmek içindir, ilk kaydı engellemez.\n`
    : `# Record Guide\n\n${link(n.system)} · ${link(n.protocol)}\n\n## Properties\n\nEvery note carries four fields: \`tags\`, \`type\`, \`updated\`, and on managed notes \`claudian_role\`. They are not decoration but **retrieval signal** — they let a note be chosen by its kind and its freshness. Whoever edits a note refreshes \`updated\` in the same edit. The role is fixed: rename the note and it is still found.\n\n## The skeleton of a note\n\nWork and method notes may carry these sections. None is compulsory — a section with nothing in it is left out rather than invented.\n\n| Section | What it holds |\n| --- | --- |\n| Why it exists | which need, which problem |\n| Directive | your own sentence, quoted |\n| Tried and failed | what was tried, what it hit, why it was dropped |\n| What worked | the decision and its reason |\n| Your step | the part you did by hand or approved |\n| Boundary | when this does not apply |\n\n## Making it readable\n\nYour own sentence stays in a \`>\` quote strip — a distilled summary does not replace it, because the exact words are the evidence. State and comparison become a table. Command output, logs and code stay in a fence as evidence. Each item opens with a bold claim; the rest explains it.\n\n## What links are for\n\nThe entry map routes; content lives in one canonical note. Neurons are **maps** (MOC — Map of Content): index notes that gather a subject and link to its notes.\n\n## Where a new record goes\n\nSomething worth keeping is never dropped because no suitable note was found. It first enters its nearest note as one line:\n\n| Fact | Note |\n| --- | --- |\n| dated work | ${link(n.reminders)} |\n| an open item with no date | ${link(n.panel)} |\n| a preference, a like, an identity claim | ${link(n.about)} |\n| how to work with you | ${link(n.agreements)} |\n| a decision · a rejected path | ${link(n.decisions)} |\n| ongoing work | ${link(n.projects)} |\n| a cost paid once | ${link(n.lessons)} |\n\nAs the same subject returns, lines accumulate and it gets its own heading in that note. When the heading grows to three paragraphs, or five or six records on one subject feel scattered, it gets its own note and map. A map opens from below, by accumulation; a note is never opened from above for an empty subject. The "do not open a new note" measure is for splitting, not for a first record.\n`);

  return {notes: out, names: {...n, entry: map}};
};

// One adapter note per connected application. The protocol is shared; this is the surface.
const adapter = (language, host, {label, mechanism}, names) => {
  const tr = language === 'tr';
  const body = tr
    ? `# ${label} — Adaptör\n\n${`[[${names.system.replace(/\.md$/, '')}]]`}\n\nBu dosya ${label} uygulamasının bu hafızaya bağlanma katmanıdır. Protokolün kendisi değil; yüzeye özgü olan kısmı taşır.\n\n## Otorite sırası\n\n1. Senin o anki sözün.\n2. ${`[[${names.protocol.replace(/\.md$/, '')}]]`}\n3. Bu adaptör.\n\n## Bu yüzeyin mekanizması\n\n${mechanism.tr}\n\n## Oturum davranışı\n\nOkuma sırası: giriş haritası → çalışma anlaşmaları ve kararlar → varsa panel ve hatırlatıcılar → konuyla ilgili not. Protokol açılışta değil, **yazmadan önce** okunur.\n\nNormal hafıza okuma ve yazma işlemleri sohbette raporlanmaz. Erişilemediğinde veya kayda değer bir yazma başarısız olduğunda tek satırla söylenir.\n\n## Süreklilik\n\nBu yüzeye özgü, senin açıkça benimsediğin veya reddettiğin kalıcı davranışlar burada gelişir. Ortak gerçeklere genellenmez; gizli akıl yürütme ve anlık davranış kaydedilmez.\n`
    : `# ${label} — Adapter\n\n${`[[${names.system.replace(/\.md$/, '')}]]`}\n\nThis file is how ${label} connects to this memory. It is not the protocol; it carries only what is specific to this surface.\n\n## Order of authority\n\n1. Your current statement.\n2. ${`[[${names.protocol.replace(/\.md$/, '')}]]`}\n3. This adapter.\n\n## How this surface connects\n\n${mechanism.en}\n\n## Session behaviour\n\nReading order: the entry map → working agreements and decisions → the panel and reminders if they exist → the note the topic needs. The protocol is read before writing, not at startup.\n\nRoutine memory reads and writes are not reported in the conversation. When access fails, or a valuable save fails, it is stated in one line.\n\n## Continuity\n\nDurable behaviour you explicitly adopted or rejected on this surface develops here. It is not generalized to shared facts; hidden reasoning and one-off behaviour are not recorded.\n`;
  const policy = require('./policy.cjs');
  const memory = policy.ACCOUNT_MEMORY.includes(host) ? '\n' + policy.memorySection(language, label) : '';
  return {file: `${label}.md`, body: front(language, {tags: ['claudian', tr ? 'adaptör' : 'adapter'], kind: tr ? 'sistem' : 'system', role: 'adapter:' + host}) + body + memory};
};

module.exports = {notes, adapter, entryName, ROLES};
