'use strict';
window.claudianError = (message, language) => {
 const pairs = [
 ['Geçerli bir ad girin.','Enter a valid name.'],['Tam klasör yolu gerekli.','Choose an absolute folder path.'],['En az bir desteklenen AI seçin.','Select at least one AI application.'],['Not ortamını seçin.','Choose a notes application.'],
 ['Hafıza için ayrı bir klasör seçin.','Choose a dedicated folder for your notes.'],['Seçilen yol bir klasör değil.','The selected path is not a folder.'],['Mevcut not klasörü bulunamadı.','The existing notes folder could not be found.'],['Yeni hafıza için boş veya yeni bir klasör seçin. Mevcut klasör için diğer seçeneği kullanın.','Choose an empty folder, or select “Use existing notes”.'],
 ['Kurulum zaten çalışıyor.','Installation is already running.'],['Bu cihazda bir hafıza zaten kurulu.','Memory is already configured. Use Add connection.'],['Genişletilecek hafıza bulunamadı.','No existing memory configuration was found.'],['Bağlantı eklerken mevcut not ortamı değiştirilemez.','The notes folder cannot change while adding a connection.'],['Bu AI bağlantısı zaten kurulu.','This AI connection is already installed.'],
 ['Bağlantı/junction içeren yol kullanılamıyor. Gerçek klasörü seçin.','Symbolic links are not supported. Choose the actual folder.'],['Yapılandırma okunamadı; mevcut dosya korundu.','The configuration could not be read. The existing file was preserved.'],['Kurulum önizlemesini yeniden oluşturun.','Review the installation again before continuing.'],['Kurulum iptal edildi.','Installation cancelled.'],['Dosya doğrulaması başarısız.','File verification failed.'],['Klasör henüz hazır değil.','The folder is not ready yet.'],['Önce kurulumu tamamlayın.','Complete setup first.'],
 ['Başlangıç kuralı zaten var; mevcut bağlantı korunuyor.','Startup instructions already exist. The existing connection was preserved.'],['Başlangıç kuralı zaten var; mevcut dosya korunuyor.','Startup instructions already exist. The existing file was preserved.'],['Global talimat dosyası çok büyük; otomatik kural eklenmedi.','The global instructions file is too large. No instructions were added.'],['Google başlangıç talimatı 12000 karakter sınırını aşıyor; mevcut dosya korundu.','Google startup instructions exceed 12,000 characters. The existing file was preserved.'],['Gemini bağlam dosyası adı desteklenmiyor; ayarlar korundu.','The Gemini context filename is unsupported. Settings were preserved.'],
 ['Hafıza kaydı değişmiş; kurulum durduruldu.','The memory configuration changed. Installation stopped.'],['Ortak bağlantı önizlemeden sonra değişti.','A shared connection changed after preview. Review setup again.'],['Önizlemeden sonra talimat dosyası değişti. Yeniden inceleyin.','Instructions changed after preview. Review setup again.'],['Önizlemeden sonra bir hedef dosya oluştu. Mevcut içerik korunuyor.','A target file appeared after preview. Existing content was preserved.'],['Talimat dosyası kurulum sırasında değişti.','Instructions changed during installation.'],['Talimat dosyası değişti; yeniden deneyin.','Instructions changed. Please try again.'],
 ['Lütfen devam eden işlemi bekleyin.','Please wait for the current operation.'],['Bağlantı bulunamadı.','Connection not found.'],['Hafıza yapılandırılmadı.','Memory is not configured.'],['Yerel okuma/yazma kontrolü başarısız.','Local read/write check failed.'],['Bağlantı dosyası değiştirilmiş. Kaldırmadan önce yapılandırmayı inceleyin.','A connection file was modified. Review its configuration before removing it.'],['Kaldırma sırasında yapılandırma değişti. Yeniden deneyin.','Configuration changed during removal. Please try again.'],['Geçersiz dil.','Invalid language.'],['Desteklenmeyen bağlam dosyası adı.','Unsupported context filename.']
 ];
 for (const [tr,en] of pairs) if(message===tr||message===en)return language==='tr'?tr:en;
 if(language==='en'&&message.includes("skill'i zaten var"))return 'A Claudian skill already exists for this application. Its files were preserved. Review the existing configuration.';
 if(language==='en'&&message.startsWith('Claudian Memory Protocol.md zaten var'))return 'Claudian Memory Protocol.md already exists. Review its configuration before continuing.';
 return message;
};
