'use strict';
const api=window.claudian, content=document.querySelector('#content'), errorBox=document.querySelector('#error');
let state, draft, plan, language='en', extending=false, busy=false, complete=false, events=[], view='home', removing=null, notice='';
const setup=document.body.dataset.surface==='setup';
const t=(en,tr)=>language==='tr'?tr:en;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(en,tr,action,primary=false,extra='')=>`<button data-action="${action}" class="${primary?'primary':''}" ${extra}>${t(en,tr)}</button>`;
function error(e){errorBox.textContent=window.claudianError(e.message,language);errorBox.hidden=false;}
function capture(){if(!document.querySelector('#name'))return;for(const k of ['name','vault','storage','mode'])draft[k]=document.querySelector('#'+k).value;draft.hosts=[...document.querySelectorAll('[name=host]:checked')].map(x=>x.value);draft.language=language;}
function header(){document.documentElement.lang=language;document.querySelector('header .caption').innerHTML=`<label for="language">${t('Language','Dil')}</label><select id="language" ${busy?'disabled':''}><option value="en" ${language==='en'?'selected':''}>English</option><option value="tr" ${language==='tr'?'selected':''}>Türkçe</option></select>`;const nav=document.querySelector('nav');if(nav){nav.hidden=extending;nav.innerHTML=`<button data-view="home">${t('Memory','Hafıza')}</button><button data-view="connections">${t('Connections','Bağlantılar')}</button><button data-view="companion">${t('Companion · In development','Yol arkadaşı · Geliştiriliyor')}</button>`;nav.querySelectorAll('button').forEach(n=>n.classList.toggle('active',n.dataset.view===view));}}
function renderSetup(){
 if(complete){content.innerHTML=`<h1>${t('Your connections are configured.','Bağlantıların yapılandırıldı.')}</h1><p>${t('Restart your AI application to load its memory instructions. It may request permission to access your notes.','Hafıza talimatlarını yüklemek için AI uygulamanı yeniden aç. Notlarına erişim izni isteyebilir.')}</p><p class="path">${esc(state.profile.vault)}</p><div class="actions">${btn('Open folder','Klasörü aç','vault')}${btn('Open Claudian','Claudian’ı aç','enter',true)}</div>`;return;}
 if(busy||events.length){const stages=[['prepare',t('Check installation','Kurulumu kontrol et')],['notes',t('Prepare notes','Notları hazırla')],['skills',t('Configure connections','Bağlantıları yapılandır')],['verify',t('Check saved files','Yazılan dosyaları kontrol et')]];const done=stages.filter(([id])=>events.some(e=>e.stage===id&&e.status==='done')).length;content.innerHTML=`<h1>${t('Setting up Claudian','Claudian kuruluyor')}</h1><progress max="4" value="${done}" aria-label="${t('Installation progress','Kurulum ilerlemesi')}"></progress>${stages.map(([id,title])=>`<div class="summary-row"><span>${title}</span><span>${events.some(e=>e.stage===id&&e.status==='done')?t('Done','Tamamlandı'):t('Waiting','Bekliyor')}</span></div>`).join('')}<p>${t('Detailed diagnostic messages are saved in the installation log.','Ayrıntılı tanılama mesajları kurulum günlüğüne kaydedilir.')}</p><div class="actions">${btn('Open log folder','Günlük klasörü','logs')}${busy?btn('Cancel','İptal et','cancel'):btn('Try again','Yeniden dene','retry')}</div>`;return;}
 if(plan){content.innerHTML=`<h1>${t('Connect your memory','Hafızanı bağla')}</h1><p>${t('Your selected AI applications will receive a memory skill and startup instructions. Existing global instructions are backed up before changes.','Seçtiğin AI uygulamalarına hafıza skill’i ve başlangıç talimatları eklenecek. Değişiklikten önce mevcut global talimatlar yedeklenir.')}</p><p class="path">${esc(draft.vault)}</p><p>${draft.hosts.map(id=>esc(state.hosts.find(h=>h.id===id).label)).join(' · ')}</p><p>${t('New protocol language: English. Existing notes are preserved.','Yeni protokol dili: Türkçe. Mevcut notlar korunur.')}</p><details><summary>${t('Review file changes','Dosya değişikliklerini incele')} (${plan.files.length})</summary><ul class="file-list">${plan.files.map(f=>`<li>${esc(f.path)}</li>`).join('')}</ul></details><p>${t('This configures local files; it does not grant account access. You can remove connections later without deleting your notes.','Bu işlem yerel dosyaları yapılandırır; hesap erişimi vermez. Bağlantıları daha sonra notlarını silmeden kaldırabilirsin.')}</p><div class="actions">${btn('Back','Geri','back')}${btn('Approve and connect','Onayla ve bağla','install',true)}</div>`;return;}
 const locked=extending?'disabled':'';
 content.innerHTML=`<h1>${extending?t('Add a connection','Bağlantı ekle'):t('Set up your memory','Hafızanı hazırla')}</h1><p>${t('Choose where your notes live and which AI applications can use them.','Notlarının konumunu ve onları kullanacak AI uygulamalarını seç.')}</p><div class="grid"><div><label for="name">${t('Your name','Adın')}</label><input id="name" maxlength="100" value="${esc(draft.name)}" ${locked}></div><div><label for="storage">${t('Note application','Not uygulaması')}</label><select id="storage" ${locked}><option value="markdown" ${draft.storage==='markdown'?'selected':''}>Markdown</option><option value="obsidian" ${draft.storage==='obsidian'?'selected':''}>Obsidian</option></select></div></div><label for="vault">${t('Notes folder','Not klasörü')}</label><div class="row"><input id="vault" value="${esc(draft.vault)}" ${locked}>${btn('Browse','Gözat','folder',false,locked)}</div><label for="mode">${t('Folder usage','Klasör kullanımı')}</label><select id="mode" ${locked}><option value="new" ${draft.mode==='new'?'selected':''}>${t('New / empty folder','Yeni / boş klasör')}</option><option value="existing" ${draft.mode==='existing'?'selected':''}>${t('Use existing notes','Mevcut notları kullan')}</option></select><fieldset><legend>${t('AI applications','AI uygulamaları')}</legend>${state.hosts.filter(h=>!extending||!state.profile.hosts.some(p=>p.id===h.id)).map(h=>`<label class="check"><input name="host" type="checkbox" value="${h.id}" ${draft.hosts.includes(h.id)?'checked':''}>${esc(h.label)}</label>`).join('')}</fieldset><p>${t('The selected language applies to new protocol files. Existing notes will not be translated or replaced.','Seçilen dil yeni protokol dosyalarına uygulanır. Mevcut notlar çevrilmez veya değiştirilmez.')}</p><div class="actions">${extending?btn('Cancel','Vazgeç','exit-setup'):'<span></span>'}${btn('Continue','Devam et','preview',true)}</div>`;
}
async function renderPanel(){const p=state.profile;
 if(view==='companion'){
 content.innerHTML=`<div class="companion-heading"><div><h1>${t('Context panel','Bağlam paneli')}</h1><p>${t('Companion in development · Connected to your web workspace','Yol arkadaşı geliştiriliyor · Web çalışma alanına bağlı')}</p></div><div class="toolbar">${btn('Reload','Yenile','companion-reload')}${btn('Sign out','Oturumu kapat','companion-logout')}</div></div><div id="companion-slot"><p id="companion-status" role="status">${t('Opening secure access-code sign-in…','Güvenli access code girişi açılıyor…')}</p><p>${t('Sign in with your website access code. This panel uses your web workspace and requires internet; it does not upload your local notes folder.','Websitesindeki access code ile giriş yap. Bu panel web çalışma alanını kullanır ve internet gerektirir; yerel not klasörünü yüklemez.')}</p></div>`;
 document.body.classList.add('companion-active');
 await api.companion('show',{y:document.querySelector('#companion-slot').getBoundingClientRect().top});return;
 }
 if(!p)throw new Error('Memory is not configured.');
 const hosts=await api.connections();
 content.innerHTML=`<h1>${view==='home'?t('Your memory','Hafızan'):t('AI connections','AI bağlantıları')}</h1>${notice?`<p role="status">${esc(notice)}</p>`:''}`;
 if(view==='home'){const notes=await api.activity();content.insertAdjacentHTML('beforeend',`<section class="vault-section"><h2>${t('Notes folder','Not klasörü')}</h2><p class="path">${esc(p.vault)}</p><div class="toolbar">${btn('Open in Obsidian','Obsidian’da aç','obsidian',true)}${btn('Open folder','Klasörü aç','vault')}${btn('Check local files','Yerel dosyaları kontrol et','check')}</div><p>${t('Local checks confirm files and folder access, not AI model behavior.','Yerel kontrol, dosyaları ve klasör erişimini doğrular; AI modelinin davranışını doğrulamaz.')}</p><details><summary>${t('Recent notes','Son notlar')}</summary>${notes.length?notes.map(n=>`<div class="note-row"><span>${esc(n.name)}</span><time>${new Date(n.modified).toLocaleDateString(language)}</time></div>`).join(''):`<p>${t('No notes yet.','Henüz not yok.')}</p>`}</details></section>`);}
 content.insertAdjacentHTML('beforeend',`<section><div class="toolbar"><h2>${t('Connections','Bağlantılar')}</h2>${state.hosts.some(h=>!p.hosts.some(x=>x.id===h.id))?btn('Add connection','Bağlantı ekle','add-hosts'):''}</div>${hosts.length?hosts.map(h=>`<div class="connection"><div class="row"><div><strong>${esc(h.label)}</strong><span class="badge">${h.status==='ready'?t('Files installed','Dosyalar kurulu'):t('Needs attention','Kontrol gerekli')}</span></div>${btn('Remove','Kaldır','remove',false,`data-host="${h.id}"`)}</div><details><summary>${t('Configuration','Yapılandırma')}</summary>${h.files.map(f=>`<div class="config-file"><span>${t(f.kind==='skill'?'Memory skill':'Startup instructions',f.kind==='skill'?'Hafıza skill’i':'Başlangıç talimatı')}</span><p class="path">${esc(f.path)}</p>${btn('Show file','Dosyayı göster','configuration',false,`data-host="${h.id}" data-kind="${f.kind}"`)}<span class="badge">${t({ready:'Installed',missing:'Missing',changed:'Modified',unreadable:'Unreadable'}[f.status],{ready:'Kurulu',missing:'Eksik',changed:'Değiştirilmiş',unreadable:'Okunamıyor'}[f.status])}</span></div>`).join('')}</details>${removing===h.id?`<div class="remove-confirm"><p>${t('Remove this connection? Your notes stay. Files still used by other connections are kept. Restart this AI application afterward.','Bu bağlantı kaldırılsın mı? Notların ve diğer bağlantıların kullandığı dosyalar korunur. Ardından bu AI uygulamasını yeniden başlat.')}</p>${btn('Keep connection','Bağlantıyı koru','dismiss-remove')}${btn('Remove connection','Bağlantıyı kaldır','confirm-remove',false,`data-host="${h.id}"`)}</div>`:''}</div>`).join(''):`<p>${t('No AI connections. Add one whenever you are ready; your notes are still here.','AI bağlantısı yok. Hazır olduğunda ekleyebilirsin; notların burada kalır.')}</p`}<p>${t('Restart your AI application after changing connections. Folder permissions remain under its control.','Bağlantıları değiştirdikten sonra AI uygulamanı yeniden başlat. Klasör izinleri o uygulamanın kontrolündedir.')}</p></section>`);
}
async function render(){await api.companion('hide');document.body.classList.remove('companion-active');header();return setup||extending?renderSetup():renderPanel();}
document.addEventListener('change',async e=>{if(e.target.id!=='language')return;try{capture();language=e.target.value;await api.preferences(language);plan=null;if(draft)draft.language=language;await render();}catch(err){error(err);}});
document.addEventListener('click',async e=>{const nav=e.target.closest('[data-view]');if(nav&&!busy){view=nav.dataset.view;notice='';await render();return;}const el=e.target.closest('[data-action]');if(!el||busy&&el.dataset.action!=='cancel')return;el.disabled=true;errorBox.hidden=true;try{const a=el.dataset.action;
 if(a==='add-hosts'){extending=true;plan=null;events=[];complete=false;const d=await api.discover();draft={name:state.profile.name,vault:state.profile.vault,storage:state.profile.storage,mode:'existing',action:'extend',language,hosts:d.suggested.hosts.filter(id=>!state.profile.hosts.some(h=>h.id===id))};await render();}
 if(a==='folder'){capture();const folder=await api.chooseFolder();if(folder){draft.vault=folder;draft.mode='existing';}await render();}
 if(a==='preview'){capture();plan=await api.prepare(draft);await render();}
 if(a==='back'||a==='retry'){plan=null;events=[];await render();}
 if(a==='install'){busy=true;events=[];await render();try{await api.install(plan.id);state=await api.snapshot();complete=true;}finally{busy=false;await render();}}
 if(a==='cancel')await api.cancel();
 if(a==='enter'||a==='exit-setup'){if(extending){extending=false;complete=false;events=[];plan=null;await render();}else await api.enter();}
 if(a==='vault'||a==='logs')await api.open(a);
 if(a==='obsidian')await api.obsidian();
 if(a==='configuration')await api.configuration(el.dataset.host,el.dataset.kind);
 if(a==='companion-reload')await api.companion('reload');
 if(a==='companion-logout')await api.companion('logout');
 if(a==='remove'){removing=el.dataset.host;await render();}
 if(a==='dismiss-remove'){removing=null;await render();}
 if(a==='confirm-remove'){busy=true;try{await api.removeHost(el.dataset.host);state=await api.snapshot();removing=null;notice=t('Connection removed. Your notes were preserved.','Bağlantı kaldırıldı. Notların korundu.');}finally{busy=false;}await render();}
 if(a==='check'){const r=await api.checkFiles();notice=r.connections.every(h=>h.status==='ready')?t('Local files and folder access are ready.','Yerel dosyalar ve klasör erişimi hazır.'):t('Folder access works. Review connections marked “Needs attention”.','Klasör erişimi çalışıyor. “Kontrol gerekli” bağlantılarını incele.');await render();}
 }catch(err){error(err);}finally{if(el.isConnected)el.disabled=false;}});
api.onProgress(e=>{events.push(e);if(busy&&(setup||extending))renderSetup();});
(async()=>{language=(await api.preferences()).language;state=await api.snapshot();if(setup){draft=(await api.discover()).suggested;draft.language=language;}await render();})().catch(error);

api.onCompanion?.(s=>{const el=document.querySelector('#companion-status');if(el)el.textContent=s.status==='offline'?t('The web panel could not be reached. Check your connection and select Reload.','Web paneline ulaşılamadı. Bağlantını kontrol edip Yenile seçeneğini kullan.'):s.status==='ready'?'':t('Loading your workspace…','Çalışma alanın yükleniyor…');});
new ResizeObserver(()=>{const slot=document.querySelector('#companion-slot');if(slot)api.companion('resize',{y:slot.getBoundingClientRect().top});}).observe(document.body);
